version: '2'
services:
    mongo:
        container_name: mongo
        image: mongo
        # We use mongostorage data volume and we will use the /data/db path for the database inside the container
        volumes: 
            - mongostorage:/data/db
        expose:
            - 27017
        ports:
            - 27017:27017
        networks:
            - sensor-reciever-network
    sensor-reciever-server:   
        build:
            context: .
            dockerfile: sensor-reciever-dockerfile.server
        image: sensor-reciever:latest
        expose:
            - 8090
        ports:
            - 8090
        networks:
            - sensor-reciever-network
        links:
            - mongo:mongo
        volumes:
            - sensor-repo:/var/lib/sensor/repo
        logging:
            driver: json-file    
    lb:
        image: dockercloud/haproxy
        ports: 
            - 80:8090
        links:
            - sensor-reciever-server:sensor-reciever-server
        networks:
            - sensor-reciever-network
    sensor-emulator-server:   
        build:
            context: .
            dockerfile: sensor-emulator-dockerfile.server
        image: sensor-emulator:latest
        networks:
            - sensor-reciever-network
        links:
            - lb:lb
        volumes:
            - sensor-emulator-repo:/var/lib/sensor-emulator/repo
        logging:
            driver: json-file   
networks:
    sensor-reciever-network:
        driver: bridge
volumes:
    sensor-repo:
        external: true
    mongostorage:
        external: true
    sensor-emulator-repo:
        external: true
        
